# Generated by Django 4.1.7 on 2023-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('motor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current', models.IntegerField(max_length=255)),
                ('voltage', models.IntegerField(max_length=255)),
            ],
        ),
    ]
