# Generated by Django 4.1.7 on 2023-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gail_Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VoltageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='motor',
            name='current',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='voltage',
        ),
        migrations.AddField(
            model_name='motor',
            name='current',
            field=models.ManyToManyField(to='Gail_Backend.currentlist'),
        ),
        migrations.AddField(
            model_name='motor',
            name='voltage',
            field=models.ManyToManyField(to='Gail_Backend.voltagelist'),
        ),
    ]
