# Generated by Django 4.1.7 on 2023-03-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gail_Backend', '0002_currentlist_voltagelist_remove_motor_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='motor',
            name='current',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='voltage',
        ),
        migrations.DeleteModel(
            name='CurrentList',
        ),
        migrations.DeleteModel(
            name='VoltageList',
        ),
        migrations.AddField(
            model_name='voltage',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gail_Backend.motor'),
        ),
        migrations.AddField(
            model_name='current',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gail_Backend.motor'),
        ),
    ]
